[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/"
  to = "/de"
  status = 302

# Proxy to Vercel
[[redirects]]
  from = "/*"
  to = "https://blw-agricultural-market-data-platform.now.sh/:splat"
  force = true
  status = 200