name: Tests CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck

      - name: "Wait Vercel deploy"
        uses: interactivethings/ixt-scripts/.github/workflows/wait-vercel-deploy@main
        id: deployment-url
        env:
          VERCEL_PROJECT: QmZSbL5YTcU238YSiotopwWT6jVmV3BXbgRKVxjtZnJK35
          VERCEL_TEAM: team_QR1NbYAXZYW9kP1RAF8UIjLl
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: "Install Playwright"
        uses: ./.github/workflows/install-playwright

      - name: Run playwright
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.deployment-url.outputs.deployment-url }}
        run: node scripts/e2e-screenshots.mjs
